# End-to-End Project on SMS Spam Classification


# Team members
1.Chennupati Renu Sree-21BAI1776
2.Babburi Maneesha-21BAI1662

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [34]:
dataset=pd.read_csv('spam.csv')

In [35]:
dataset.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [36]:
dataset['spam']=dataset['Category'].apply(lambda x: 1 if x=="spam" else 0)

In [37]:
dataset

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [38]:
X=dataset.iloc[:,1].values
y=dataset.iloc[:,-1].values

In [39]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [40]:
cv=CountVectorizer()
x_train_count=cv.fit_transform(X_train)

In [41]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [42]:
model=MultinomialNB()
model.fit(x_train_count,y_train)

MultinomialNB()

In [43]:
email_ham=["How are you doing??"]
email_ham_count=cv.transform(email_ham)


In [44]:
result=model.predict(email_ham_count)
result

array([0], dtype=int64)

In [47]:
email_spam=["you won 100000 ruppeeees Call to 91739691810"]
email_spam_count=cv.transform(email_spam)
model.predict(email_spam_count)

array([1], dtype=int64)

In [48]:
X_test_count=cv.transform(X_test)
model.predict(X_test_count)

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

In [49]:
model.score(X_test_count,y_test)

0.9877961234745154